spring.application.name=localAI

server.port=8080
spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=gemma3:4b
#spring.ai.ollama.base-url=http://4.217.177.102:11434/
spring.ai.ollama.chat.model=gemma3:latest
#spring.ai.ollama.chat.model=gpt-oss:latest
#spring.ai.ollama.chat.model=llama3.2:latest
cwa.api.key=CWA-5C3CCB9A-4002-41C6-9E9C-76ACF7006141
# ... ????? ...

# ?? Agents ??????? (??????????)
# ?? Windows: D:/project/AI??/agents-main
# ?? Mac/Linux: /Users/username/Downloads/agents-main
# ???????????????
agents.path=./agents

